import { expect, test } from '@playwright/test'
import sharp from 'sharp'

for (const width of [320, 1280]) {
test(`profile picture preview, cancel, save and removal persist at ${width}px`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/login')
  await page.getByLabel('Name', { exact: true }).fill('Picture Player')
  await page.getByLabel('Email').fill(`picture-${width}-${Date.now()}@example.com`)
  await page.getByRole('button', { name: 'SIGN IN (DEV)' }).click()
  await page.getByRole('button', { name: 'Account menu for Picture Player' }).click()
  await page.getByRole('menuitem', { name: 'Change profile picture' }).click()
  await expect(page).toHaveURL(/\/me#picture$/)
  const editor = page.locator('#picture')
  await expect(editor).toBeFocused()
  const input = editor.getByLabel('Choose profile picture', { exact: true })
  const file = { name: 'picture.png', mimeType: 'image/png', buffer: await sharp({ create: { width: 400, height: 200, channels: 3, background: '#8740bb' } }).png().toBuffer() }
  await input.setInputFiles(file)
  await expect(editor.getByText('Square crop preview.', { exact: false })).toBeVisible()
  await expect(editor.locator('img')).toHaveAttribute('src', /^data:image\/png/)
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(editor.locator('img')).toHaveCount(0)
  await input.setInputFiles(file)
  await editor.getByRole('button', { name: 'Save picture', exact: true }).click()
  await expect(editor.getByRole('status')).toHaveText('Profile picture saved.')
  await expect(editor.locator('img')).toHaveAttribute('src', /^\/api\/avatars\//)
  await expect(editor.locator('img')).toHaveJSProperty('naturalWidth', 256)
  await editor.scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath(`picture-${width}.png`) })
  await page.reload()
  await expect(editor.locator('img')).toHaveAttribute('src', /^\/api\/avatars\//)
  await editor.getByRole('button', { name: 'Remove picture', exact: true }).click()
  await expect(editor.locator('img')).toHaveCount(0)
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(editor.locator('img')).toHaveAttribute('src', /^\/api\/avatars\//)
  await editor.getByRole('button', { name: 'Remove picture', exact: true }).click()
  await editor.getByRole('button', { name: 'Save picture', exact: true }).click()
  await expect(editor.getByRole('status')).toHaveText('Profile picture removed.')
  await page.reload()
  await expect(editor).toBeVisible()
  await expect(editor.locator('img')).toHaveCount(0)
  await input.setInputFiles({ name: 'bad.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg/>') })
  await expect(editor.getByRole('alert')).toContainText('Choose a JPG, PNG or WebP')
})
}
