import { expect, test, type Page } from '@playwright/test'

async function signIn(page: Page, name: string) {
  await page.goto('/login')
  await page.getByLabel('Name', { exact: true }).fill(name)
  await page.getByLabel('Email').fill(`training-${name}-${Date.now()}-${Math.random()}@example.com`)
  await page.getByRole('button', { name: 'SIGN IN (DEV)' }).click()
  await expect(page.getByRole('button', { name: 'NEW LEAGUE' })).toBeVisible()
}
async function dart(page: Page, entry: string) {
  await page.getByLabel('Enter dart hits').fill(entry)
  const saved = page.waitForResponse((response) => response.url().endsWith('/actions') && response.request().method() === 'POST')
  await page.getByRole('button', { name: /^ADD DARTS?$/ }).click()
  expect((await saved).status()).toBe(200)
  await expect(page.getByLabel('Enter dart hits')).toBeEnabled()
  await expect(page.getByLabel('Enter dart hits')).toHaveValue('')
}

test('solo nine-dart practice persists, undoes and records progress without a competition result', async ({ page }, info) => {
  await signIn(page, 'Solo')
  await page.getByRole('link', { name: 'TRAINING', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Training arena', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Nine-dart challenge.*SOLO OR MULTIPLAYER/ }).click()
  await page.getByRole('button', { name: 'START NINE-DART CHALLENGE' }).click()
  await expect(page.getByRole('heading', { name: 'Nine-dart challenge' })).toBeVisible()
  const url = page.url()
  await dart(page, 'T20')
  await expect(page.locator('.training-player > strong')).toHaveText('60')
  await page.reload()
  await expect(page.locator('.training-player > strong')).toHaveText('60')
  await page.getByRole('button', { name: 'UNDO LAST DART' }).click()
  await expect(page.locator('.training-player > strong')).toHaveText('0')
  await page.getByLabel('Enter dart hits').fill('T20 180 T20')
  await expect(page.getByRole('alert')).toContainText('possible single dart')
  await expect(page.getByRole('button', { name: 'ADD DARTS', exact: true })).toBeDisabled()
  await expect(page.locator('.training-player > strong')).toHaveText('0')
  await page.getByRole('button', { name: 'Clear entry' }).click()
  // Keypad taps compose rather than immediately saving; more than a visit is allowed.
  for (let i = 0; i < 4; i++) await page.getByRole('button', { name: 'T20', exact: true }).click()
  await expect(page.getByLabel('Enter dart hits')).toHaveValue('T20 T20 T20 T20')
  await expect(page.locator('.calc-display > strong')).toHaveText('240')
  await expect(page.locator('.training-player > strong')).toHaveText('0')
  await page.getByRole('button', { name: 'ADD DARTS', exact: true }).click()
  await expect(page.locator('.training-player > strong')).toHaveText('240')
  await page.reload()
  await expect(page.locator('.training-player > strong')).toHaveText('240')
  await page.getByRole('button', { name: 'UNDO LAST DART' }).click()
  await expect(page.locator('.training-player > strong')).toHaveText('180')
  await dart(page, 'T20,T20 + T20 T20 T20')
  await page.getByRole('button', { name: 'MISS', exact: true }).click()
  await page.getByRole('button', { name: 'ADD DART', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Training complete' })).toBeVisible()
  await expect(page.locator('.training-player > strong')).toHaveText('480')
  await expect(page.getByLabel('Enter dart hits')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Training complete' })).toBeVisible()
  await page.getByRole('link', { name: /VIEW PROGRESS/ }).click()
  await page.getByLabel('Progress challenge').selectOption('nine-dart')
  await expect(page.locator('.stat-tile').filter({ hasText: 'PERSONAL BEST' })).toContainText('480')
  await expect(page.getByRole('table', { name: /Monthly nine-dart scores/ })).toContainText('480.0')
  await expect(page.locator('.training-session-link')).toHaveCount(1)
  for (const width of [1280, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath(`training-arena-${width}.png`), fullPage: true })
  }
  await page.getByRole('button', { name: 'Account menu for Solo' }).click()
  await page.getByRole('menuitem', { name: 'Light theme' }).click()
  await page.keyboard.press('Escape')
  await page.screenshot({ path: info.outputPath('training-arena-mobile-light.png'), fullPage: true })
  await page.goto('/me')
  await expect(page.getByText('No completed matches yet', { exact: true })).toBeVisible()
  await page.getByRole('group', { name: 'Stats category' }).getByRole('button', { name: 'Training', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Training stats' }).getByText('WIN RATE')).toHaveCount(0)
  await page.goto(url)
  await page.getByRole('button', { name: 'DELETE', exact: true }).click()
  await page.getByRole('button', { name: 'REMOVE SESSION' }).click()
  await expect(page.getByRole('heading', { name: 'Training arena' })).toBeVisible()
  await expect(page.locator('.training-session-link')).toHaveCount(0)
})

for (const challenge of [
  { name: 'Around the clock', start: 'START AROUND THE CLOCK', entry: Array.from({ length: 20 }, (_, i) => `${i % 2 ? 'D' : 'T'}${i + 1}`).join(' '), score: '20/20' },
  { name: 'Nine-dart challenge', start: 'START NINE-DART CHALLENGE', entry: Array(9).fill('T20').join(' '), score: '540' },
]) {
  test(`${challenge.name} accepts an entire solo challenge in one batch on mobile and desktop`, async ({ page }, info) => {
    await signIn(page, 'Batch')
    await page.goto('/training')
    await page.getByRole('button', { name: new RegExp(`${challenge.name}.*SOLO OR MULTIPLAYER`) }).click()
    await page.getByRole('button', { name: challenge.start }).click()
    const input = page.getByLabel('Enter dart hits')
    await input.fill(`${challenge.entry} MISS`)
    await expect(page.getByRole('alert')).toBeVisible()
    await expect(page.getByRole('button', { name: 'ADD DARTS', exact: true })).toBeDisabled()
    await expect(page.locator('.training-darts li')).toHaveCount(0)
    await input.fill(challenge.entry)
    await expect(page.getByRole('alert')).toHaveCount(0)
    for (const width of [1280, 768, 390, 320]) {
      await page.setViewportSize({ width, height: 844 })
      await expect(input).toBeVisible()
      await expect(page.getByRole('button', { name: 'ADD DARTS', exact: true })).toBeEnabled()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await page.screenshot({ path: info.outputPath(`batch-entry-${width}.png`), fullPage: true })
    }
    await page.getByRole('button', { name: 'Account menu for Batch' }).click()
    await page.getByRole('menuitem', { name: 'Light theme' }).click()
    await page.keyboard.press('Escape')
    await page.screenshot({ path: info.outputPath('batch-entry-mobile-light.png'), fullPage: true })
    if (challenge.name === 'Around the clock') await input.press('Enter')
    else await page.getByRole('button', { name: 'ADD DARTS', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Training complete' })).toBeVisible()
    await expect(page.locator('.training-player > strong')).toHaveText(challenge.score)
    await page.reload()
    await expect(page.locator('.training-player > strong')).toHaveText(challenge.score)
    await expect(page.getByRole('heading', { name: 'Training complete' })).toBeVisible()
  })
}

test('batch controls pause while saving and keep the entry after a rejected save', async ({ page }) => {
  await signIn(page, 'Retry')
  await page.goto('/training')
  await page.getByRole('button', { name: /Nine-dart challenge.*SOLO OR MULTIPLAYER/ }).click()
  await page.getByRole('button', { name: 'START NINE-DART CHALLENGE' }).click()
  const input = page.getByLabel('Enter dart hits')
  await input.fill('T20 T20 T20 T20')
  let release!: () => void
  const gate = new Promise<void>((resolve) => { release = resolve })
  let submissions = 0
  await page.route('**/api/training/*/actions', async (route) => {
    submissions++
    await gate
    await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Temporarily unavailable' }) })
  })
  await page.getByRole('button', { name: 'ADD DARTS', exact: true }).click()
  await expect(input).toBeDisabled()
  await expect(page.getByRole('button', { name: 'T20', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'ADD DARTS', exact: true })).toBeDisabled()
  release()
  await expect(page.getByRole('alert')).toContainText('Temporarily unavailable')
  await expect(input).toBeEnabled()
  await expect(input).toHaveValue('T20 T20 T20 T20')
  await expect(page.locator('.training-player > strong')).toHaveText('0')
  expect(submissions).toBe(1)
  await page.unroute('**/api/training/*/actions')
  await dart(page, 'T20 T20 T20 T20')
  await expect(page.locator('.training-player > strong')).toHaveText('240')
})

test('league players train together across devices and clock progress stays separate', async ({ page, browser }, info) => {
  await signIn(page, 'Host')
  const leagueResponse = await page.request.post('/api/leagues', { data: { name: 'Practice crew' } })
  expect(leagueResponse.status()).toBe(201)
  const { league } = await leagueResponse.json()
  const otherContext = await browser.newContext()
  const other = await otherContext.newPage()
  // Separate signed-in identity, connected through the league invite.
  await other.goto(`${new URL(page.url()).origin}/login`)
  await other.getByLabel('Name', { exact: true }).fill('Partner')
  await other.getByLabel('Email').fill(`partner-${Date.now()}@example.com`)
  await other.getByRole('button', { name: 'SIGN IN (DEV)' }).click()
  await expect(other.getByRole('button', { name: 'NEW LEAGUE' })).toBeVisible()
  expect((await other.request.post(`/api/invites/${league.inviteCode}/join`, { data: {} })).ok()).toBe(true)
  await page.goto('/training')
  await page.getByLabel('Play space').selectOption(league.id)
  await page.getByRole('button', { name: 'Partner', exact: true }).click()
  await page.getByRole('button', { name: 'START AROUND THE CLOCK' }).click()
  await expect(page.getByRole('heading', { name: 'Around the clock' })).toBeVisible()
  await other.goto(page.url())
  await expect(other.getByRole('heading', { name: 'Host’s turn' })).toBeVisible()
  // A batch follows the existing three-dart player rotation, including a partial next turn.
  await dart(page, 'T1 D2 3 MISS')
  await expect(other.getByRole('heading', { name: 'Partner’s turn' })).toBeVisible({ timeout: 8000 })
  await expect(page.locator('.training-player').filter({ hasText: 'Host' })).toContainText('3/20')
  await expect(page.locator('.training-player').filter({ hasText: 'Partner' })).toContainText('1/60 darts', { timeout: 8000 })
  await other.getByRole('button', { name: 'UNDO LAST DART' }).click()
  await expect(page.locator('.training-player').filter({ hasText: 'Partner' })).toContainText('0/60 darts', { timeout: 8000 })
  // Both players can enter darts on a shared board. Finish each target in order.
  for (let target = 1; target <= 20; target++) {
    const current = await page.request.get(new URL(page.url()).pathname.replace('/training/', '/api/training/'))
    const { session } = await current.json()
    if (session.status === 'completed') break
    // Finish up to six throws per iteration, using each current player's actual next target.
    for (let n = 0; n < 6; n++) {
      const response = await page.request.get(`/api/training/${session.id}`)
      const state = (await response.json()).session
      if (state.status === 'completed') break
      const result = state.results[state.state.active]
      const saved = await page.request.post(`/api/training/${session.id}/actions`, { data: { baseVersion: state.version, action: { type: 'submit', entry: String(result.hits + 1) } } })
      expect(saved.status()).toBe(200)
    }
  }
  await expect(other.getByRole('heading', { name: 'Training complete' })).toBeVisible({ timeout: 8000 })
  await expect(page.getByRole('heading', { name: 'Training complete' })).toBeVisible({ timeout: 8000 })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('multiplayer-clock-results.png'), fullPage: true })
  await page.goto('/training')
  await expect(page.locator('.stat-tile').filter({ hasText: 'BEST TARGETS HIT' })).toContainText('20/20')
  await expect(page.locator('.stat-tile').filter({ hasText: 'QUICKEST FULL CLOCK' })).toContainText('20 darts')
  await page.getByLabel('Progress challenge').selectOption('nine-dart')
  await expect(page.locator('.stat-tile').filter({ hasText: 'SESSIONS' })).toContainText('0')
  await page.getByLabel('Play space').selectOption(league.id)
  await page.getByRole('button', { name: 'PLAY BOTS' }).click()
  await expect(page.getByRole('button', { name: 'Add Rookie Rue, level 1, Novice' })).toBeVisible()
  const dialog = page.getByRole('dialog')
  await dialog.locator('.member-picker').getByRole('button', { name: 'Partner', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'START MATCH' })).toBeDisabled()
  await expect(dialog.locator('.sheet-summary')).toHaveText('Choose at least one bot for training')
  await dialog.getByRole('button', { name: 'Add Rookie Rue, level 1, Novice' }).click()
  await expect(dialog.getByRole('button', { name: 'START MATCH' })).toBeEnabled()
  await otherContext.close()
})
