import { expect, test, type Page } from '@playwright/test'

async function signIn(page: Page, name: string) {
  await page.goto('/login')
  await page.getByLabel('Name', { exact: true }).fill(name)
  await page.getByLabel('Email').fill(`training-${name}-${Date.now()}-${Math.random()}@example.com`)
  await page.getByRole('button', { name: 'SIGN IN (DEV)' }).click()
  await expect(page.getByRole('button', { name: 'NEW ROOM' })).toBeVisible()
}
async function dart(page: Page, entry: string) {
  await page.getByLabel('Training dart').fill(entry)
  await page.getByRole('button', { name: 'ADD DART', exact: true }).click()
  await expect(page.getByLabel('Training dart')).toBeEnabled()
}

test('solo nine-dart practice persists, undoes and records progress without a competition result', async ({ page }, info) => {
  await signIn(page, 'Solo')
  await page.getByRole('link', { name: 'TRAINING', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Training arena', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Nine-dart challenge.*SOLO OR MULTIPLAYER/ }).click()
  await page.getByRole('button', { name: 'START NINE-DART CHALLENGE' }).click()
  await expect(page.getByRole('heading', { name: 'Nine-dart challenge' })).toBeVisible()
  const url = page.url()
  await dart(page, 'T20')
  await expect(page.locator('.training-player > strong')).toHaveText('60')
  await page.reload()
  await expect(page.locator('.training-player > strong')).toHaveText('60')
  await page.getByRole('button', { name: 'UNDO LAST DART' }).click()
  await expect(page.locator('.training-player > strong')).toHaveText('0')
  await dart(page, '180')
  await expect(page.getByRole('alert')).toContainText('possible single dart')
  await expect(page.locator('.training-player > strong')).toHaveText('0')
  for (let i = 0; i < 8; i++) await dart(page, 'T20')
  await page.getByRole('button', { name: 'MISS', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Training complete' })).toBeVisible()
  await expect(page.locator('.training-player > strong')).toHaveText('480')
  await expect(page.getByLabel('Training dart')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Training complete' })).toBeVisible()
  await page.getByRole('link', { name: /VIEW PROGRESS/ }).click()
  await page.getByLabel('Progress challenge').selectOption('nine-dart')
  await expect(page.locator('.stat-tile').filter({ hasText: 'PERSONAL BEST' })).toContainText('480')
  await expect(page.getByRole('table', { name: /Monthly nine-dart scores/ })).toContainText('480.0')
  await expect(page.locator('.training-session-link')).toHaveCount(1)
  for (const width of [1280, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath(`training-arena-${width}.png`), fullPage: true })
  }
  await page.getByRole('button', { name: 'Account menu for Solo' }).click()
  await page.getByRole('menuitem', { name: 'Light theme' }).click()
  await page.keyboard.press('Escape')
  await page.screenshot({ path: info.outputPath('training-arena-mobile-light.png'), fullPage: true })
  await page.goto('/me')
  await expect(page.getByText('No completed matches yet', { exact: true })).toBeVisible()
  await page.getByRole('group', { name: 'Stats category' }).getByRole('button', { name: 'Training', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Training stats' }).getByText('WIN RATE')).toHaveCount(0)
  await page.goto(url)
  await page.getByRole('button', { name: 'DELETE', exact: true }).click()
  await page.getByRole('button', { name: 'REMOVE SESSION' }).click()
  await expect(page.getByRole('heading', { name: 'Training arena' })).toBeVisible()
  await expect(page.locator('.training-session-link')).toHaveCount(0)
})

test('room players train together across devices and clock progress stays separate', async ({ page, browser }, info) => {
  await signIn(page, 'Host')
  const roomResponse = await page.request.post('/api/rooms', { data: { name: 'Practice crew' } })
  expect(roomResponse.status()).toBe(201)
  const { room } = await roomResponse.json()
  const otherContext = await browser.newContext()
  const other = await otherContext.newPage()
  // Separate signed-in identity, connected through the room invite.
  await other.goto(`${new URL(page.url()).origin}/login`)
  await other.getByLabel('Name', { exact: true }).fill('Partner')
  await other.getByLabel('Email').fill(`partner-${Date.now()}@example.com`)
  await other.getByRole('button', { name: 'SIGN IN (DEV)' }).click()
  await expect(other.getByRole('button', { name: 'NEW ROOM' })).toBeVisible()
  expect((await other.request.post(`/api/invites/${room.inviteCode}/join`, { data: {} })).ok()).toBe(true)
  await page.goto('/training')
  await page.getByLabel('Play space').selectOption(room.id)
  await page.getByRole('button', { name: 'Partner', exact: true }).click()
  await page.getByRole('button', { name: 'START AROUND THE CLOCK' }).click()
  await expect(page.getByRole('heading', { name: 'Around the clock' })).toBeVisible()
  await other.goto(page.url())
  await expect(other.getByRole('heading', { name: 'Host’s turn' })).toBeVisible()
  await dart(page, 'T1')
  await dart(page, 'D2')
  await dart(page, '3')
  await expect(other.getByRole('heading', { name: 'Partner’s turn' })).toBeVisible({ timeout: 8000 })
  await dart(other, 'MISS')
  await expect(page.locator('.training-player').filter({ hasText: 'Partner' })).toContainText('1/60 darts', { timeout: 8000 })
  await other.getByRole('button', { name: 'UNDO LAST DART' }).click()
  await expect(page.locator('.training-player').filter({ hasText: 'Partner' })).toContainText('0/60 darts', { timeout: 8000 })
  // Both players can enter darts on a shared board. Finish each target in order.
  for (let target = 1; target <= 20; target++) {
    const current = await page.request.get(new URL(page.url()).pathname.replace('/training/', '/api/training/'))
    const { session } = await current.json()
    if (session.status === 'completed') break
    // Finish up to six throws per iteration, using each current player's actual next target.
    for (let n = 0; n < 6; n++) {
      const response = await page.request.get(`/api/training/${session.id}`)
      const state = (await response.json()).session
      if (state.status === 'completed') break
      const result = state.results[state.state.active]
      const saved = await page.request.post(`/api/training/${session.id}/actions`, { data: { baseVersion: state.version, action: { type: 'submit', entry: String(result.hits + 1) } } })
      expect(saved.status()).toBe(200)
    }
  }
  await expect(other.getByRole('heading', { name: 'Training complete' })).toBeVisible({ timeout: 8000 })
  await expect(page.getByRole('heading', { name: 'Training complete' })).toBeVisible({ timeout: 8000 })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('multiplayer-clock-results.png'), fullPage: true })
  await page.goto('/training')
  await expect(page.locator('.stat-tile').filter({ hasText: 'BEST TARGETS HIT' })).toContainText('20/20')
  await expect(page.locator('.stat-tile').filter({ hasText: 'QUICKEST FULL CLOCK' })).toContainText('20 darts')
  await page.getByLabel('Progress challenge').selectOption('nine-dart')
  await expect(page.locator('.stat-tile').filter({ hasText: 'SESSIONS' })).toContainText('0')
  await page.getByLabel('Play space').selectOption(room.id)
  await page.getByRole('button', { name: 'PLAY BOTS' }).click()
  await expect(page.getByRole('button', { name: 'Add Rookie Rue, level 1, Novice' })).toBeVisible()
  const dialog = page.getByRole('dialog')
  await dialog.locator('.member-picker').getByRole('button', { name: 'Partner', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'START MATCH' })).toBeDisabled()
  await expect(dialog.locator('.sheet-summary')).toHaveText('Choose at least one bot for training')
  await dialog.getByRole('button', { name: 'Add Rookie Rue, level 1, Novice' }).click()
  await expect(dialog.getByRole('button', { name: 'START MATCH' })).toBeEnabled()
  await otherContext.close()
})
